# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false
    app.form.registration:
        class: PST4Bundle\Form\RegistrationFormType
        tags:
          - { name: "form.type", alias: "app_user_registration" }

    app.form.invitation:
        class: PST4Bundle\Form\InvitationFormType
        arguments: ['@app.form.data_transformer.invitation']
        tags:
          - { name: "form.type", alias: "app_invitation_type" }

    app.form.data_transformer.invitation:
        class: PST4Bundle\Form\DataTransformer\InvitationToCodeTransformer
        arguments: ['@doctrine.orm.entity_manager']
        public: false